name: Docker Auto-Build & Push with Mapping

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine changed folders
        id: changes
        run: |
          echo "Detecting changed folders..."
          CHANGED_FOLDERS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F/ '{print $1}' | sort -u)
          echo "Changed folders: $CHANGED_FOLDERS"
          echo "CHANGED_FOLDERS=$CHANGED_FOLDERS" >> $GITHUB_ENV

      - name: Build & push Docker images based on mapping
        run: |
          # Define folder → Docker repo mapping
          declare -A FOLDER_MAP
          FOLDER_MAP[frontend]="healthsense_frontend"
          FOLDER_MAP[backend]="healthsense_node_backend"
          FOLDER_MAP[ml_backend]="healthsense_ml_backend"

          for folder in $CHANGED_FOLDERS; do
            if [ -f "$folder/Dockerfile" ]; then
              # Determine the Docker repo name from the mapping
              IMAGE_NAME=${FOLDER_MAP[$folder]}
              if [ -z "$IMAGE_NAME" ]; then
                echo "⚠️ No mapping found for folder '$folder', skipping..."
                continue
              fi

              FULL_IMAGE="arshah22/$IMAGE_NAME:latest"
              echo "✅ Building and pushing Docker image: $FULL_IMAGE"
              docker build -t $FULL_IMAGE $folder
              docker push $FULL_IMAGE
            else
              echo "⏭ No Dockerfile in $folder, skipping..."
            fi
          done
